sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t grapefruit-web .
  - docker tag grapefruit-web $DOCKER_USERNAME/grapefruit-web
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push bashkirtsevich/grapefruit-web:latest
